"""add source flashcard

Revision ID: 46f8cb8463e4
Revises: 067826d8ec58
Create Date: 2026-06-30 15:27:10.841517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46f8cb8463e4'
down_revision: Union[str, Sequence[str], None] = '067826d8ec58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('source_flashcard_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_flashcards_source_flashcard_id'), 'flashcards', ['source_flashcard_id'], unique=False)
    op.create_foreign_key(None, 'flashcards', 'flashcards', ['source_flashcard_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.drop_index(op.f('ix_flashcards_source_flashcard_id'), table_name='flashcards')
    op.drop_column('flashcards', 'source_flashcard_id')
    # ### end Alembic commands ###
