"""add reading_romaji and example_romaji to flashcards

Revision ID: 77cdc0fd0db6
Revises: a5a061aaae73
Create Date: 2026-07-01 12:11:45.827602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cdc0fd0db6'
down_revision: Union[str, Sequence[str], None] = 'a5a061aaae73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('reading_romaji', sa.String(length=255), nullable=True))
    op.add_column('flashcards', sa.Column('example_romaji', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'example_romaji')
    op.drop_column('flashcards', 'reading_romaji')
    # ### end Alembic commands ###
