"""add new_cards_per_day to user_settings

Revision ID: a5a061aaae73
Revises: 46f8cb8463e4
Create Date: 2026-06-30 20:22:00.126797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5a061aaae73'
down_revision: Union[str, Sequence[str], None] = '46f8cb8463e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('new_cards_per_day', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'new_cards_per_day')
    # ### end Alembic commands ###
